export const BREADCRUMBS_SET = 'BREADCRUMBS_SET';
export const BREADCRUMBS_RESET = 'BREADCRUMBS_RESET';

export const LOADING_INCREMENT = 'LOADING_INCREMENT';
export const LOADING_DECREMENT = 'LOADING_DECREMENT';

export const TIPS_UPDATE = 'TIPS_UPDATE';

export const GET_ASIDE_LINKS = 'GET_ASIDE_LINKS';

export const RESET_PREV_ASIDE_LINKS  = 'RESET_PREV_ASIDE_LINKS';

export const TOGGLE_SIDEBAR  = 'TOGGLE_SIDEBAR';


