export const BREADCRUMBS_SET = 'BREADCRUMBS_SET';
export const BREADCRUMBS_RESET = 'BREADCRUMBS_RESET';

export const LOADING_INCREMENT = 'LOADING_INCREMENT';
export const LOADING_DECREMENT = 'LOADING_DECREMENT';

export const TIPS_UPDATE = 'TIPS_UPDATE';


